# Generated by Django 3.2.7 on 2021-10-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('Apellidos', models.CharField(max_length=60)),
                ('No_documento', models.IntegerField()),
                ('Direccion', models.CharField(max_length=60)),
                ('Telefono', models.IntegerField()),
                ('Telefono1', models.IntegerField()),
                ('Ciudad', models.CharField(max_length=60)),
                ('Nombre_responsable', models.CharField(max_length=60)),
                ('Telefono_responsable', models.IntegerField()),
                ('Telefono1_responsable', models.IntegerField()),

            ],
        ),
    ]
