# Generated by Django 3.2.7 on 2021-10-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Psp_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='nombre',
            new_name='Nombres',
        ),
    ]
