# Generated by Django 3.2.7 on 2021-10-25 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Psp_App', '0002_rename_nombre_pacientes_nombres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pacientes',
        ),
    ]
