# Generated by Django 3.2.8 on 2021-10-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Psp_App', '0003_delete_pacientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=60)),
                ('Apellidos', models.CharField(max_length=60)),
                ('No_documento', models.IntegerField()),
                ('Direccion', models.CharField(max_length=60)),
                ('Telefono', models.IntegerField()),
                ('Telefono1', models.IntegerField()),
                ('Ciudad', models.CharField(max_length=60)),
                ('Nombre_responsable', models.CharField(max_length=60)),
                ('Telefono_responsable', models.IntegerField()),
                ('Telefono1_responsable', models.IntegerField()),

            ]
        )
    ]
