# Generated by Django 3.2.7 on 2021-11-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Psp_App', '0005_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='diagnostico',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='nota',
            name='estado_en_eps',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nota',
            name='estado_tratamiento',
            field=models.CharField(max_length=115),
        ),
        migrations.AlterField(
            model_name='nota',
            name='profesional_en_gestion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nota',
            name='tratamiento',
            field=models.CharField(max_length=110),
        ),
    ]
